language: java
git:
  depth: 1
jdk:
  - openjdk8
dist: trusty
cache:
  directories:
    - "$HOME/.m2"
    - '$HOME/.sonar/cache'
addons:
  sonarcloud:
    organization: "oliviercailloux-github"
script:
#  - sonar-scanner
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

